export enum ParticipantRole {
  HOST = 'HOST',
  MODERATOR = 'MODERATOR',
  GUEST = 'GUEST',
}

export enum WorkspaceRole {
  OWNER = 'OWNER',
  ADMIN = 'ADMIN',
  MEMBER = 'MEMBER',
}

export enum RoomStatus {
  IDLE = 'IDLE',
  ACTIVE = 'ACTIVE',
  ENDED = 'ENDED',
}

export enum RecordingStatus {
  RECORDING = 'RECORDING',
  STOPPED = 'STOPPED',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
}

export enum MeetingEventType {
  ROOM_CREATED = 'ROOM_CREATED',
  ROOM_STARTED = 'ROOM_STARTED',
  ROOM_ENDED = 'ROOM_ENDED',
  PARTICIPANT_JOINED = 'PARTICIPANT_JOINED',
  PARTICIPANT_LEFT = 'PARTICIPANT_LEFT',
  PARTICIPANT_MUTED = 'PARTICIPANT_MUTED',
  PARTICIPANT_UNMUTED = 'PARTICIPANT_UNMUTED',
  RECORDING_STARTED = 'RECORDING_STARTED',
  RECORDING_STOPPED = 'RECORDING_STOPPED',
  CHAT_MESSAGE_SENT = 'CHAT_MESSAGE_SENT',
}
